#!/usr/bin/env bash
# Installs Nginx with the following configurations
# Listen to port 80.
# Return a page containing the server that served the page
# at the root with the curl GET request

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	index	index.html;

	location /redirect_me {
	    return 301 https://cuberule.com;
	}

	error_page 404 /404.html;
	location /404 {
	    root /etc/nginx/html;
	    internal;
	}

	location / {
	    add_header X-Served-By $HOSTNAME;
}
}
" > /etc/nginx/sites-available/default

service nginx restart
