#!/usr/bin/env bash
# Outputs the subdomain, its record type and its destination
# shellcheck disable=SC2086

query_dns() {
  dig "$1.$2" +noall +answer | awk '
  {
    # Print the record type and destination
    printf "The subdomain %s is a " $4 " record and points to " $5 "\n", "'$1'"
  }'
}

# check if at least one argument (domain) is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

if [ -z "$2" ]; then
  for sub in www lb-01 web-01 web-02; do
    query_dns "$sub" "$1"
  done
else
  query_dns "$2" "$1"
fi