#!/usr/bin/env bash
# Transfer a file between client and a server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no "$4" "$1" "$3@$2":~
