#!/usr/bin/env bash
# Install Ngnx with the following configuration
# Listent to port 80.
# Return a page containig  "Hello World!" when required
# at the root with the curl GET request

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	index	index.html;
}
" > /etc/nginx/sites-available/default

service nginx restart
