#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get update
apt-get install -y haproxy=2.8.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "backend web-backend
    balance roundrobin
    server web-01 web-01.vilet.tech:80 check
    server web-02 web-02.vilet.tech:80 check

frontend http
    bind *:80
    mode http
    default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

update-rc.d haproxy defaults
chmod +x /etc/init.d/haproxy

service haproxy start
service haproxy restart

